blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/markhazleton/react-native-web-start/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/markhazleton/react-native-web-start/tree/main/documentation
    about: Browse comprehensive setup guides and technical documentation
  - name: 🌟 Live Demo
    url: https://markhazleton.github.io/react-native-web-start
    about: Try the live demo with in-app documentation browser
